### PR TITLE
Update pronto-fasterer.gemspec

### LINKED ISSUE #16: Fasterer semantic version is too strict
At the moment pronto-fasterer requires `~> 0.10.0`.

This rules out the new version 0.11.0: https://github.com/DamirSvrtan/fasterer/pull/106#issuecomment-1818204102

Can it be relaxed to `~> 0.10`? ie allow higher minor versions?

### PR DESCRIPTION
**Pull request by KieranP**
Fixed #16 

cc @ashkulz

### CODE REVIEW

**Comment by ashkulz** [comment]
@KieranP have you tested that it works properly?

**Comment by campbecf** [comment]
@ashkulz @KieranP We may want to consider something like
```
s.add_runtime_dependency('fasterer', '>= 0.11', '< 1.0')
```

Since we've had to have a PR for each minor version bump. 

See:
https://github.com/prontolabs/pronto-fasterer/pull/9
https://github.com/prontolabs/pronto-fasterer/pull/12
https://github.com/prontolabs/pronto-fasterer/pull/14

I'm testing this on a fork I've made.

**Comment by campbecf** [comment]
No issues using fasterer 0.11 so far. Specs pass as well.

**Comment by KieranP** [comment]
@campbecf Thanks for the recommendation. Have changed to `('fasterer', '>= 0.10', '< 1.0')`

**Comment by hlascelles** [comment]
@ashkulz can we get a new gem cut please? The latest release does not have this change yet... https://rubygems.org/gems/pronto-fasterer/versions/0.11.2

Thanks in advance!

**Comment by Viktor-Ivliev** [comment]
@hlascelles It looks like you should just use direct links to the git hub. 
`gem 'pronto-fasterer', github: 'prontolabs/pronto-fasterer', require: false`
Maybe there will be a hero who will support all this, but for now we say thanks for what we have. 
https://github.com/prontolabs/pronto-rubocop/issues/92

**Comment by ashkulz** [comment]
My mother was in and out of the hospital for just over a month, I've picked up a persistent infection during this period and also dealing with deadlines at work 🫠

Sorry for dropping the ball for pronto, will be making releases tomorrow.

**Comment by Viktor-Ivliev** [comment]
@ashkulz  good health to you and your family.

**Comment by ashkulz** [comment]
[`0.11.3`](https://rubygems.org/gems/pronto-fasterer/versions/0.11.3) has been released to RubyGems. Publishing future versions should be simpler due to implementation of Trusted Publishing workflow (4c981e398bb8f9a089110cb34a07dedceae6fdce) :grin:

**Pull request merged**
